/**
 * @studio/c2s — Connect2Souls domain logic (groups, mentees, sessions, join requests).
 * UI stays in apps/web (M1) and apps/c2s-public. See docs/CORE_ENGINE_C2S_PLAN.md.
 */
export {
  C2S_JOIN_REQUEST_WORKFLOW_TYPE,
  canManageC2SGroup,
  getMentorGroups,
  getAllC2SGroupsWithMentees,
  updateGroupProfile,
  listPublicC2SGroups,
  createC2SJoinRequest,
  syncC2SJoinRequestFromWorkflow,
  createC2SSession,
  getC2SSessionsForGroup,
  updateC2SSession,
  deleteC2SSession,
  getSessionGroupId,
  createMenteeInGroup,
  updateMentee,
  deleteMentee,
  getMenteeGroupId,
  getMentorJoinRequests,
  listAdminC2SGroups,
  listAdminC2SMentees,
  createAdminC2SGroup,
  updateAdminC2SGroup,
  deleteAdminC2SGroup,
  createAdminC2SMentee,
  updateAdminC2SMentee,
  deleteAdminC2SMentee,
  toC2SKanbanApprovalRow,
  listC2SJoinRequestKanbanRows,
  type UpdateGroupProfileInput,
  type CreateJoinRequestInput,
  type CreateSessionInput,
  type UpdateSessionInput,
  type MenteeInput,
  type MentorJoinRequest,
  type AdminCreateGroupInput,
  type AdminUpdateGroupInput,
  type AdminMenteeInput,
  type AdminUpdateMenteeInput,
  type C2SKanbanApprovalRow,
} from './src/service';

export {
  initialsOf,
  listClusterOverviews,
  getClusterForHead,
  getClustersForCoordinator,
  createCluster,
  updateCluster,
  deleteCluster,
  listCoordinators,
  assignCoordinator,
  removeCoordinator,
  listMentors,
  assignMentor,
  removeMentor,
  PIPELINE_STATUSES,
  listPipeline,
  assignPipelineCoordinator,
  assignPipelineMentor,
  schedulePipelineInterview,
  updatePipelineStatus,
  updatePipelineNotes,
  createRecommendedPipelineEntry,
  averageAssignmentDays,
  listRecentActivity,
  listMenteesForMentor,
  listMenteesForClusters,
  listAllMentees,
  listGroupMembers,
  type ActivityItem,
  getDevotionEntries,
  logDevotionEntry,
  devotionStreak,
  addTraining,
  removeTraining,
  endorseMentee,
  listEndorsedMentees,
  deactivateMentee,
  transferMentee,
  type WorkerSummary,
  type ClusterOverview,
  type ClusterInput,
  type CoordinatorSummary,
  type MentorSummary,
  type PipelineStatus,
  type PipelineEntry,
} from './src/hierarchy';

export {
  recentMonths,
  menteeGrowth,
  assignmentTrend,
  potentialMenteeTrend,
  menteesByBarangay,
  menteesByMentor,
  churchWideStats,
  type MonthBucket,
  type GrowthPoint,
  type AssignmentPoint,
  type NamedCount,
  type ChurchWideStats,
} from './src/reports';
